[project]
name = "humor-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.5",
    "openai>=2.15.0",
    "pydantic-ai>=0.0.19",
    "pydantic-settings>=2.11.0",
    "pydantic>=2.12.5",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]

[dependency-groups]
dev = ["ruff>=0.13.0"]
